# Generated by Django 3.0.5 on 2021-03-10 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210310_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_of_add',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
